###########
# site.title

title:    'RLSpaceInvaders'
subtitle: 'CS 175: Project in AI'
repo_url: 'https://github.com/zachlai23/RLGalaga'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
